/*
   users
       
   emails
   compony
   cars
   customer
   session

*/


/*
  APIS
     - CUSTOMERS TABLE USER_ID  KELGANDA USHBU USERGA TEGISHLI
                              - USER    -> ALL
                              - CAR_TITLE
                              - COMPENY_TITLE

      - SESSION TABLE USER_ID KELGANDA USHBU USERGA TEGISHLI
                              - USER  -> ALL
                              - START_AT
                              - END_AT

     
     - USERS TABLE  COMPANY_ID KELGANDA USHBU COMPANY_ID TEGISHLI
                              - USERS -> ALL

     - CARS TABLE COMPANY_ID KELGANDA USHBU COMPANY_ID TEGISHLI
                              - CAR  -> ALL

     - COMPANY TABLE EMAIL_ID KELGANDA USHBU EMAIL_ID TEGISHLI
                              - EMAIL_TITLE
                              - COMPANY -> ALL

     - CARS TABLE  ID KELGANDA USHBU ID TEGISHLI
                              - CAR_TITLE
                              - COMPANY_TITLE


*/