POST http://localhost:5000/register
Content-Type: application/json

{
    "username": "Anvar",
    "email": "anvar@email",
    "password": "anvar1234"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
   
    "suppername": "anvar@email",
    "password": "anvar1234"
}



###

POST http://localhost:5000/create
Content-Type: application/json

 {
        "title": "nestjs",
        "price": "800000",
        "author": "Eshmat Toshmatov",
        "userId": "3943c883-3680-4f02-bc01-98fa19b078de"
}

###
GET http://localhost:5000/list
Content-Type: application/json
headers: 400a30ef-6d60-4f6c-984d-98c939ccf7b8
